name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'llama_stack/**'
      - 'tests/unit/**'
      - 'uv.lock'
      - 'pyproject.toml'
      - 'requirements.txt'
      - '.github/workflows/unit-tests.yml' # This workflow
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.12"
          - "3.13"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: ./.github/actions/setup-runner

      - name: Run unit tests
        run: |
          PYTHON_VERSION=${{ matrix.python }} ./scripts/unit-tests.sh --junitxml=pytest-report-${{ matrix.python }}.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: test-results-${{ matrix.python }}
          path: |
            .pytest_cache/
            pytest-report-${{ matrix.python }}.xml
            htmlcov-${{ matrix.python }}/
          retention-days: 7

      - name: Check Coverage
        run: |
          coverage=$(uv run --python ${{ matrix.python }} --group unit coverage report -m | tail -1 | tail -c 4 | head -c 2)
          echo "Total coverage: ${coverage}%"

          # Check if coverage is below the threshold
          if (( ${coverage} < 40 )); then
              echo "Coverage failed at ${coverage}%, expected at least 40%"
              exit 1
          else
              echo "Coverage check passed with ${coverage}%"
          fi
